// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sergkegfyuiihimonihe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlcmdrZWdmeXVpaWhpbW9uaWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDAzMzIsImV4cCI6MjA2NjIxNjMzMn0.RtHkGYxmNiBDS2zTrYkP5NLcqlKM0DWwy9_zFjRwdes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);